/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.madhur;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 91940
 */
public class Modify_User extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    Connection connection;
    PreparedStatement preparedStatement;

    public Modify_User() throws ClassNotFoundException, SQLException {
        initComponents();
        Class.forName("com.mysql.cj.jdbc.Driver");
        connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/madhur", "root", "My$ql123");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        username = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        login = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        username1 = new javax.swing.JLabel();
        first_name = new javax.swing.JTextField();
        modify = new javax.swing.JButton();
        back = new javax.swing.JButton();
        dob = new javax.swing.JTextField();
        username4 = new javax.swing.JLabel();
        username5 = new javax.swing.JLabel();
        last_name = new javax.swing.JTextField();
        username6 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        username7 = new javax.swing.JLabel();
        mobile_number = new javax.swing.JTextField();
        hnufjg = new javax.swing.JLabel();
        username8 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        username10 = new javax.swing.JLabel();
        enter_username = new javax.swing.JTextField();
        username11 = new javax.swing.JLabel();
        gender = new javax.swing.JTextField();
        username2 = new javax.swing.JLabel();
        adhar_card_number = new javax.swing.JTextField();
        username12 = new javax.swing.JLabel();
        bank_name = new javax.swing.JTextField();
        account_num = new javax.swing.JTextField();
        ifsc = new javax.swing.JTextField();
        username13 = new javax.swing.JLabel();
        username14 = new javax.swing.JLabel();
        get_Details = new javax.swing.JButton();

        username.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        username.setText("username:-");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 51));

        login.setFont(new java.awt.Font("Kruti Dev 040 ", 1, 36)); // NOI18N
        login.setText("Modify User Details");

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setAlignmentX(1.0F);
        jSeparator2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        username1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        username1.setText("Username:-");

        first_name.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        first_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                first_nameActionPerformed(evt);
            }
        });

        modify.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        modify.setText("Modify");
        modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyActionPerformed(evt);
            }
        });

        back.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        dob.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobActionPerformed(evt);
            }
        });

        username4.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        username4.setText("Mobile Number:-");

        username5.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        username5.setText("Email Id:-");

        last_name.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        last_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                last_nameActionPerformed(evt);
            }
        });

        username6.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        username6.setText("First Name:-");

        email.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        username7.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        username7.setText("Last Name:-");

        mobile_number.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mobile_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobile_numberActionPerformed(evt);
            }
        });

        hnufjg.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        hnufjg.setText("Gender:-");

        username8.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        username8.setText("Permanent Address:-");

        address.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });

        username10.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        username10.setText("Adhar Card Number:-");

        enter_username.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        enter_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enter_usernameActionPerformed(evt);
            }
        });

        username11.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N

        gender.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });

        username2.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        username2.setText("Date Of Birth:-");

        adhar_card_number.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        adhar_card_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adhar_card_numberActionPerformed(evt);
            }
        });

        username12.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        username12.setText("Bank Name:-");

        bank_name.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bank_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bank_nameActionPerformed(evt);
            }
        });

        account_num.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        account_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                account_numActionPerformed(evt);
            }
        });

        ifsc.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ifsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ifscActionPerformed(evt);
            }
        });

        username13.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        username13.setText("IFSC Code:- ");

        username14.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        username14.setText("Account Number:-");

        get_Details.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        get_Details.setText("Get Details");
        get_Details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                get_DetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(613, 613, 613)
                        .addComponent(username11))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(383, 383, 383)
                        .addComponent(modify)
                        .addGap(44, 44, 44)
                        .addComponent(back))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(username8)
                            .addGap(34, 34, 34)
                            .addComponent(address))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(hnufjg)
                                        .addComponent(username13)
                                        .addComponent(username5))
                                    .addGap(30, 30, 30)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(bank_name, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(enter_username, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(first_name, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ifsc, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(username6)
                                .addComponent(username12)
                                .addComponent(username1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(57, 57, 57)
                                            .addComponent(username10)
                                            .addGap(45, 45, 45)
                                            .addComponent(adhar_card_number, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(username2)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(username14)
                                                    .addGap(82, 82, 82)
                                                    .addComponent(account_num, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(username7)
                                                        .addGap(155, 155, 155))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(username4)
                                                        .addGap(100, 100, 100)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(mobile_number, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(last_name, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGap(34, 34, 34))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(get_Details, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(392, 392, 392))))))
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addGap(464, 464, 464)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username1)
                    .addComponent(enter_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(get_Details, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username12)
                    .addComponent(bank_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(account_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username14))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ifsc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username13)
                    .addComponent(username2)
                    .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username6)
                    .addComponent(first_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username7)
                    .addComponent(last_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username5)
                    .addComponent(username4)
                    .addComponent(mobile_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hnufjg)
                        .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(adhar_card_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(username10)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username8)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(username11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back)
                    .addComponent(modify))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void first_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_first_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_first_nameActionPerformed

    private void dobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobActionPerformed

    private void last_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_last_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_last_nameActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void mobile_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobile_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobile_numberActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void enter_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enter_usernameActionPerformed
        // TODO add your handling code here:
        enter_username.setEnabled(false);
    }//GEN-LAST:event_enter_usernameActionPerformed

    private void modifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyActionPerformed
        try {
            // TODO add your handling code here:
            String q = "update user set first_name = ?, last_name = ?, email = ?, mobile = ?, dob = ?, address= ?, gender = ? where username = ?";
            preparedStatement = connection.prepareStatement(q);
            preparedStatement.setString(1, first_name.getText());
            preparedStatement.setString(2, last_name.getText());
            preparedStatement.setString(3, email.getText());
            preparedStatement.setString(4, mobile_number.getText());
            preparedStatement.setString(5, dob.getText());
            preparedStatement.setString(6, address.getText());
            preparedStatement.setString(7, gender.getText());
            preparedStatement.setString(8, enter_username.getText());
            preparedStatement.executeUpdate();
            User updateUser = new User();
            updateUser.show();
            dispose();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Modify_User.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Modify_User.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_modifyActionPerformed

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        try {
            // TODO add your handling code here:
            Menu menu = new Menu();
            menu.show();
            dispose();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Modify_User.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Modify_User.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_backActionPerformed

    private void adhar_card_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adhar_card_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adhar_card_numberActionPerformed

    private void bank_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bank_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bank_nameActionPerformed

    private void account_numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_account_numActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_account_numActionPerformed

    private void ifscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ifscActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ifscActionPerformed

    private void get_DetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get_DetailsActionPerformed
        try {
            // TODO add your handling code here:
            preparedStatement = connection.prepareStatement("select * from user where username = ?");
            preparedStatement.setString(1, enter_username.getText());
            ResultSet rs = preparedStatement.executeQuery();

            if (rs.next()) {
                first_name.setText(rs.getString("first_name"));
                last_name.setText(rs.getString("last_name"));
                mobile_number.setText(rs.getString("mobile"));
                email.setText(rs.getString("email"));
                dob.setText(rs.getString("dob"));
                address.setText(rs.getString("address"));
                adhar_card_number.setText(rs.getString("adharcard_number"));
                adhar_card_number.setEditable(false);
                gender.setText(rs.getString("gender"));
                bank_name.setText("Moms Bank Of India");
                bank_name.setEditable(false);

                long min = 32000000000L;
                long max = 33999999999L;
                long i = (long) (Math.random() * (max - min + 1) + min);
                String s = String.valueOf(i);
                account_num.setText(s);
                account_num.setEditable(false);
                
                int min1 = 1000000;
                int max1 = 9999999;
                int l = (int) (Math.random() * (max1 - min1 + 1) + min1);
                String s1 = String.valueOf(l);
                String s2 = "MBIN";
                s2 = s2.concat(s1);
                ifsc.setText(s2);
                ifsc.setEditable(false);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Modify_User.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_get_DetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modify_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modify_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modify_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modify_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Modify_User().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Modify_User.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Modify_User.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField account_num;
    private javax.swing.JTextField address;
    private javax.swing.JTextField adhar_card_number;
    private javax.swing.JButton back;
    private javax.swing.JTextField bank_name;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField dob;
    private javax.swing.JTextField email;
    private javax.swing.JTextField enter_username;
    private javax.swing.JTextField first_name;
    private javax.swing.JTextField gender;
    private javax.swing.JButton get_Details;
    private javax.swing.JLabel hnufjg;
    private javax.swing.JTextField ifsc;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField last_name;
    private javax.swing.JLabel login;
    private javax.swing.JTextField mobile_number;
    private javax.swing.JButton modify;
    private javax.swing.JLabel username;
    private javax.swing.JLabel username1;
    private javax.swing.JLabel username10;
    private javax.swing.JLabel username11;
    private javax.swing.JLabel username12;
    private javax.swing.JLabel username13;
    private javax.swing.JLabel username14;
    private javax.swing.JLabel username2;
    private javax.swing.JLabel username4;
    private javax.swing.JLabel username5;
    private javax.swing.JLabel username6;
    private javax.swing.JLabel username7;
    private javax.swing.JLabel username8;
    // End of variables declaration//GEN-END:variables
}
